package com.supplierconsumer.security;

import com.supplierconsumer.config.AppProperties;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Proves that the Java service interoperates with credentials the Node service produced.
 *
 * <p>This matters because the replacement has to take over a live database and live sessions: if
 * either the token signatures or the password digests were incompatible, every user would be
 * silently logged out or locked out. The fixtures below were generated by running the Node
 * libraries ({@code jsonwebtoken} and {@code bcryptjs}) against the same inputs.
 */
class TokenCompatibilityTest {

    private static final String SECRET = "test-secret-that-is-at-least-32-bytes-long!!";

    /** Signed by jsonwebtoken with issuer/audience, exactly as lib/auth.js does. */
    private static final String NODE_COMPANY_TOKEN =
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJlbWFpbCI6Im93bmVyQGFjbWUudGVzdCIsInJvbG"
            + "VJZCI6Miwicm9sZU5hbWUiOiJPd25lciIsImlhdCI6MTc4OTExNjMzMywiZXhwIjoyMTA0NDc2MzMzLCJhdWQiOiJwZXJu"
            + "LXN0YWNrLXVzZXJzIiwiaXNzIjoicGVybi1zdGFjay1hcHAifQ.VbHvGvkAzu_TVYzp1pivxcUVNYxZUavOs_k8wrZrO4k";

    /** Signed by jsonwebtoken without issuer/audience, as consumerAuthController does. */
    private static final String NODE_CONSUMER_TOKEN =
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcklkIjo3LCJlbWFpbCI6ImJ1eWVyQGFjbWUudGVzdCIsInV"
            + "zZXJUeXBlIjoiY29uc3VtZXIiLCJpYXQiOjE3ODkxMTYzMzMsImV4cCI6MjEwNDQ3NjMzM30"
            + ".eJypGom27dbsEP9i43N-uM0dhrrF46XYgGUo_5bMIZM";

    /** Produced by bcryptjs at cost 12 for the password "Admin123!". */
    private static final String NODE_BCRYPT_HASH =
            "$2b$12$b6wFcAOfIZ.fGRJzEMFbDem7FMEk1cCTVV4.qinO6FrsArePko4q2";

    private final JwtService jwt = new JwtService(new AppProperties(
            new AppProperties.Wire("Asia/Almaty"),
            new AppProperties.Jwt(SECRET, SECRET, "pern-stack-app", "pern-stack-users",
                    Duration.ofMinutes(15), Duration.ofDays(7)),
            new AppProperties.Uploads("./uploads"),
            new AppProperties.SocketIo(false, "0.0.0.0", 3001),
            new AppProperties.RateLimit(false, 5, 3, Duration.ofMinutes(15))));

    @Test
    @DisplayName("a company token minted by the Node service still validates")
    void acceptsNodeCompanyToken() {
        Claims claims = jwt.verifyCompanyAccess(NODE_COMPANY_TOKEN);

        assertThat(claims.get("userId", Number.class).longValue()).isEqualTo(42L);
        assertThat(claims.get("roleName", String.class)).isEqualTo("Owner");
        assertThat(claims.getIssuer()).isEqualTo("pern-stack-app");
    }

    @Test
    @DisplayName("a consumer token minted by the Node service still validates")
    void acceptsNodeConsumerToken() {
        Claims claims = jwt.verifyConsumerAccess(NODE_CONSUMER_TOKEN);

        assertThat(claims.get("consumerId", Number.class).longValue()).isEqualTo(7L);
        assertThat(claims.get("userType", String.class)).isEqualTo("consumer");
    }

    @Test
    @DisplayName("a consumer token is rejected on the company path, because it carries no issuer")
    void consumerTokenIsNotACompanyToken() {
        assertThatThrownBy(() -> jwt.verifyCompanyAccess(NODE_CONSUMER_TOKEN))
                .isInstanceOf(JwtException.class);
    }

    @Test
    @DisplayName("a company token carries no userType, which is what keeps it off consumer routes")
    void companyTokenIsNotAConsumerToken() {
        // Both families share a signing secret, so the signature check passes here. The guard is
        // the missing claim, which the consumer authenticator tests for explicitly.
        Claims claims = jwt.verifyConsumerAccess(NODE_COMPANY_TOKEN);

        assertThat(claims.get("userType", String.class)).isNull();
    }

    @Test
    @DisplayName("tokens minted here carry the same claims the Node service produced")
    void mintsMatchingClaims() {
        Claims company = jwt.verifyCompanyAccess(
                jwt.signCompanyAccess(42, "owner@acme.test", 2, "Owner"));
        assertThat(company.getIssuer()).isEqualTo("pern-stack-app");
        assertThat(company.getAudience()).containsExactly("pern-stack-users");
        assertThat(company.get("roleId", Number.class).intValue()).isEqualTo(2);

        Claims consumer = jwt.verifyConsumerAccess(jwt.signConsumerAccess(7, "buyer@acme.test"));
        assertThat(consumer.getIssuer()).isNull();
        assertThat(consumer.get("userType", String.class)).isEqualTo("consumer");
    }

    @Test
    @DisplayName("a password hashed by bcryptjs still verifies")
    void acceptsNodeBcryptHash() {
        PasswordService passwords = new PasswordService();

        assertThat(passwords.matches("Admin123!", NODE_BCRYPT_HASH)).isTrue();
        assertThat(passwords.matches("wrong", NODE_BCRYPT_HASH)).isFalse();
    }

    @Test
    @DisplayName("a secret too short for HS256 fails at startup rather than at first login")
    void rejectsWeakSecret() {
        assertThatThrownBy(() -> new JwtService(new AppProperties(
                new AppProperties.Wire("Asia/Almaty"),
                new AppProperties.Jwt("too-short", "too-short", "pern-stack-app", "pern-stack-users",
                        Duration.ofMinutes(15), Duration.ofDays(7)),
                new AppProperties.Uploads("./uploads"),
                new AppProperties.SocketIo(false, "0.0.0.0", 3001),
                new AppProperties.RateLimit(false, 5, 3, Duration.ofMinutes(15)))))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("at least 32 bytes");
    }
}
